[package]
name = "web-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "web_core"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
insta = "1.39.0"
itertools = "0.13.0"
walkdir = "2.5.0"
